/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lab.face.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)", date = "2026-03-28")
public class EncodeRequest implements org.apache.thrift.TBase<EncodeRequest, EncodeRequest._Fields>, java.io.Serializable, Cloneable, Comparable<EncodeRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EncodeRequest");

  private static final org.apache.thrift.protocol.TField IMAGE_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("image_data", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new EncodeRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new EncodeRequestTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer image_data; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IMAGE_DATA((short)1, "image_data");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IMAGE_DATA
          return IMAGE_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IMAGE_DATA, new org.apache.thrift.meta_data.FieldMetaData("image_data", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EncodeRequest.class, metaDataMap);
  }

  public EncodeRequest() {
  }

  public EncodeRequest(
    java.nio.ByteBuffer image_data)
  {
    this();
    this.image_data = org.apache.thrift.TBaseHelper.copyBinary(image_data);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EncodeRequest(EncodeRequest other) {
    if (other.isSetImage_data()) {
      this.image_data = org.apache.thrift.TBaseHelper.copyBinary(other.image_data);
    }
  }

  @Override
  public EncodeRequest deepCopy() {
    return new EncodeRequest(this);
  }

  @Override
  public void clear() {
    this.image_data = null;
  }

  public byte[] getImage_data() {
    setImage_data(org.apache.thrift.TBaseHelper.rightSize(image_data));
    return image_data == null ? null : image_data.array();
  }

  public java.nio.ByteBuffer bufferForImage_data() {
    return org.apache.thrift.TBaseHelper.copyBinary(image_data);
  }

  public EncodeRequest setImage_data(byte[] image_data) {
    this.image_data = image_data == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(image_data.clone());
    return this;
  }

  public EncodeRequest setImage_data(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer image_data) {
    this.image_data = org.apache.thrift.TBaseHelper.copyBinary(image_data);
    return this;
  }

  public void unsetImage_data() {
    this.image_data = null;
  }

  /** Returns true if field image_data is set (has been assigned a value) and false otherwise */
  public boolean isSetImage_data() {
    return this.image_data != null;
  }

  public void setImage_dataIsSet(boolean value) {
    if (!value) {
      this.image_data = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case IMAGE_DATA:
      if (value == null) {
        unsetImage_data();
      } else {
        if (value instanceof byte[]) {
          setImage_data((byte[])value);
        } else {
          setImage_data((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case IMAGE_DATA:
      return getImage_data();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case IMAGE_DATA:
      return isSetImage_data();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof EncodeRequest)
      return this.equals((EncodeRequest)that);
    return false;
  }

  public boolean equals(EncodeRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_image_data = true && this.isSetImage_data();
    boolean that_present_image_data = true && that.isSetImage_data();
    if (this_present_image_data || that_present_image_data) {
      if (!(this_present_image_data && that_present_image_data))
        return false;
      if (!this.image_data.equals(that.image_data))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetImage_data()) ? 131071 : 524287);
    if (isSetImage_data())
      hashCode = hashCode * 8191 + image_data.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(EncodeRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetImage_data(), other.isSetImage_data());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImage_data()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.image_data, other.image_data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("EncodeRequest(");
    boolean first = true;

    sb.append("image_data:");
    if (this.image_data == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.image_data, sb);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (image_data == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'image_data' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EncodeRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public EncodeRequestStandardScheme getScheme() {
      return new EncodeRequestStandardScheme();
    }
  }

  private static class EncodeRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<EncodeRequest> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, EncodeRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IMAGE_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.image_data = iprot.readBinary();
              struct.setImage_dataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, EncodeRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.image_data != null) {
        oprot.writeFieldBegin(IMAGE_DATA_FIELD_DESC);
        oprot.writeBinary(struct.image_data);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EncodeRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public EncodeRequestTupleScheme getScheme() {
      return new EncodeRequestTupleScheme();
    }
  }

  private static class EncodeRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<EncodeRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EncodeRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeBinary(struct.image_data);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EncodeRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.image_data = iprot.readBinary();
      struct.setImage_dataIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

