/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.lab.face.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)", date = "2026-03-28")
public class FaceInfo implements org.apache.thrift.TBase<FaceInfo, FaceInfo._Fields>, java.io.Serializable, Cloneable, Comparable<FaceInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FaceInfo");

  private static final org.apache.thrift.protocol.TField ENCODING_FIELD_DESC = new org.apache.thrift.protocol.TField("encoding", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField TOP_FIELD_DESC = new org.apache.thrift.protocol.TField("top", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField RIGHT_FIELD_DESC = new org.apache.thrift.protocol.TField("right", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField BOTTOM_FIELD_DESC = new org.apache.thrift.protocol.TField("bottom", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField LEFT_FIELD_DESC = new org.apache.thrift.protocol.TField("left", org.apache.thrift.protocol.TType.I32, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new FaceInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new FaceInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.Double> encoding; // required
  public int top; // required
  public int right; // required
  public int bottom; // required
  public int left; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ENCODING((short)1, "encoding"),
    TOP((short)2, "top"),
    RIGHT((short)3, "right"),
    BOTTOM((short)4, "bottom"),
    LEFT((short)5, "left");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ENCODING
          return ENCODING;
        case 2: // TOP
          return TOP;
        case 3: // RIGHT
          return RIGHT;
        case 4: // BOTTOM
          return BOTTOM;
        case 5: // LEFT
          return LEFT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TOP_ISSET_ID = 0;
  private static final int __RIGHT_ISSET_ID = 1;
  private static final int __BOTTOM_ISSET_ID = 2;
  private static final int __LEFT_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ENCODING, new org.apache.thrift.meta_data.FieldMetaData("encoding", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    tmpMap.put(_Fields.TOP, new org.apache.thrift.meta_data.FieldMetaData("top", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.RIGHT, new org.apache.thrift.meta_data.FieldMetaData("right", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.BOTTOM, new org.apache.thrift.meta_data.FieldMetaData("bottom", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LEFT, new org.apache.thrift.meta_data.FieldMetaData("left", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FaceInfo.class, metaDataMap);
  }

  public FaceInfo() {
  }

  public FaceInfo(
    java.util.List<java.lang.Double> encoding,
    int top,
    int right,
    int bottom,
    int left)
  {
    this();
    this.encoding = encoding;
    this.top = top;
    setTopIsSet(true);
    this.right = right;
    setRightIsSet(true);
    this.bottom = bottom;
    setBottomIsSet(true);
    this.left = left;
    setLeftIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FaceInfo(FaceInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetEncoding()) {
      java.util.List<java.lang.Double> __this__encoding = new java.util.ArrayList<java.lang.Double>(other.encoding);
      this.encoding = __this__encoding;
    }
    this.top = other.top;
    this.right = other.right;
    this.bottom = other.bottom;
    this.left = other.left;
  }

  @Override
  public FaceInfo deepCopy() {
    return new FaceInfo(this);
  }

  @Override
  public void clear() {
    this.encoding = null;
    setTopIsSet(false);
    this.top = 0;
    setRightIsSet(false);
    this.right = 0;
    setBottomIsSet(false);
    this.bottom = 0;
    setLeftIsSet(false);
    this.left = 0;
  }

  public int getEncodingSize() {
    return (this.encoding == null) ? 0 : this.encoding.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.Double> getEncodingIterator() {
    return (this.encoding == null) ? null : this.encoding.iterator();
  }

  public void addToEncoding(double elem) {
    if (this.encoding == null) {
      this.encoding = new java.util.ArrayList<java.lang.Double>();
    }
    this.encoding.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.Double> getEncoding() {
    return this.encoding;
  }

  public FaceInfo setEncoding(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.Double> encoding) {
    this.encoding = encoding;
    return this;
  }

  public void unsetEncoding() {
    this.encoding = null;
  }

  /** Returns true if field encoding is set (has been assigned a value) and false otherwise */
  public boolean isSetEncoding() {
    return this.encoding != null;
  }

  public void setEncodingIsSet(boolean value) {
    if (!value) {
      this.encoding = null;
    }
  }

  public int getTop() {
    return this.top;
  }

  public FaceInfo setTop(int top) {
    this.top = top;
    setTopIsSet(true);
    return this;
  }

  public void unsetTop() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TOP_ISSET_ID);
  }

  /** Returns true if field top is set (has been assigned a value) and false otherwise */
  public boolean isSetTop() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TOP_ISSET_ID);
  }

  public void setTopIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TOP_ISSET_ID, value);
  }

  public int getRight() {
    return this.right;
  }

  public FaceInfo setRight(int right) {
    this.right = right;
    setRightIsSet(true);
    return this;
  }

  public void unsetRight() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RIGHT_ISSET_ID);
  }

  /** Returns true if field right is set (has been assigned a value) and false otherwise */
  public boolean isSetRight() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RIGHT_ISSET_ID);
  }

  public void setRightIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RIGHT_ISSET_ID, value);
  }

  public int getBottom() {
    return this.bottom;
  }

  public FaceInfo setBottom(int bottom) {
    this.bottom = bottom;
    setBottomIsSet(true);
    return this;
  }

  public void unsetBottom() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BOTTOM_ISSET_ID);
  }

  /** Returns true if field bottom is set (has been assigned a value) and false otherwise */
  public boolean isSetBottom() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BOTTOM_ISSET_ID);
  }

  public void setBottomIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BOTTOM_ISSET_ID, value);
  }

  public int getLeft() {
    return this.left;
  }

  public FaceInfo setLeft(int left) {
    this.left = left;
    setLeftIsSet(true);
    return this;
  }

  public void unsetLeft() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LEFT_ISSET_ID);
  }

  /** Returns true if field left is set (has been assigned a value) and false otherwise */
  public boolean isSetLeft() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LEFT_ISSET_ID);
  }

  public void setLeftIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LEFT_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ENCODING:
      if (value == null) {
        unsetEncoding();
      } else {
        setEncoding((java.util.List<java.lang.Double>)value);
      }
      break;

    case TOP:
      if (value == null) {
        unsetTop();
      } else {
        setTop((java.lang.Integer)value);
      }
      break;

    case RIGHT:
      if (value == null) {
        unsetRight();
      } else {
        setRight((java.lang.Integer)value);
      }
      break;

    case BOTTOM:
      if (value == null) {
        unsetBottom();
      } else {
        setBottom((java.lang.Integer)value);
      }
      break;

    case LEFT:
      if (value == null) {
        unsetLeft();
      } else {
        setLeft((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ENCODING:
      return getEncoding();

    case TOP:
      return getTop();

    case RIGHT:
      return getRight();

    case BOTTOM:
      return getBottom();

    case LEFT:
      return getLeft();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ENCODING:
      return isSetEncoding();
    case TOP:
      return isSetTop();
    case RIGHT:
      return isSetRight();
    case BOTTOM:
      return isSetBottom();
    case LEFT:
      return isSetLeft();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof FaceInfo)
      return this.equals((FaceInfo)that);
    return false;
  }

  public boolean equals(FaceInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_encoding = true && this.isSetEncoding();
    boolean that_present_encoding = true && that.isSetEncoding();
    if (this_present_encoding || that_present_encoding) {
      if (!(this_present_encoding && that_present_encoding))
        return false;
      if (!this.encoding.equals(that.encoding))
        return false;
    }

    boolean this_present_top = true;
    boolean that_present_top = true;
    if (this_present_top || that_present_top) {
      if (!(this_present_top && that_present_top))
        return false;
      if (this.top != that.top)
        return false;
    }

    boolean this_present_right = true;
    boolean that_present_right = true;
    if (this_present_right || that_present_right) {
      if (!(this_present_right && that_present_right))
        return false;
      if (this.right != that.right)
        return false;
    }

    boolean this_present_bottom = true;
    boolean that_present_bottom = true;
    if (this_present_bottom || that_present_bottom) {
      if (!(this_present_bottom && that_present_bottom))
        return false;
      if (this.bottom != that.bottom)
        return false;
    }

    boolean this_present_left = true;
    boolean that_present_left = true;
    if (this_present_left || that_present_left) {
      if (!(this_present_left && that_present_left))
        return false;
      if (this.left != that.left)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetEncoding()) ? 131071 : 524287);
    if (isSetEncoding())
      hashCode = hashCode * 8191 + encoding.hashCode();

    hashCode = hashCode * 8191 + top;

    hashCode = hashCode * 8191 + right;

    hashCode = hashCode * 8191 + bottom;

    hashCode = hashCode * 8191 + left;

    return hashCode;
  }

  @Override
  public int compareTo(FaceInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetEncoding(), other.isSetEncoding());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEncoding()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.encoding, other.encoding);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTop(), other.isSetTop());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTop()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.top, other.top);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRight(), other.isSetRight());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRight()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.right, other.right);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBottom(), other.isSetBottom());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBottom()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bottom, other.bottom);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLeft(), other.isSetLeft());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLeft()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.left, other.left);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("FaceInfo(");
    boolean first = true;

    sb.append("encoding:");
    if (this.encoding == null) {
      sb.append("null");
    } else {
      sb.append(this.encoding);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("top:");
    sb.append(this.top);
    first = false;
    if (!first) sb.append(", ");
    sb.append("right:");
    sb.append(this.right);
    first = false;
    if (!first) sb.append(", ");
    sb.append("bottom:");
    sb.append(this.bottom);
    first = false;
    if (!first) sb.append(", ");
    sb.append("left:");
    sb.append(this.left);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FaceInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FaceInfoStandardScheme getScheme() {
      return new FaceInfoStandardScheme();
    }
  }

  private static class FaceInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<FaceInfo> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, FaceInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ENCODING
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.encoding = new java.util.ArrayList<java.lang.Double>(_list0.size);
                double _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readDouble();
                  struct.encoding.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setEncodingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TOP
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.top = iprot.readI32();
              struct.setTopIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RIGHT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.right = iprot.readI32();
              struct.setRightIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // BOTTOM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.bottom = iprot.readI32();
              struct.setBottomIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LEFT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.left = iprot.readI32();
              struct.setLeftIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, FaceInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.encoding != null) {
        oprot.writeFieldBegin(ENCODING_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.DOUBLE, struct.encoding.size()));
          for (double _iter3 : struct.encoding)
          {
            oprot.writeDouble(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TOP_FIELD_DESC);
      oprot.writeI32(struct.top);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(RIGHT_FIELD_DESC);
      oprot.writeI32(struct.right);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BOTTOM_FIELD_DESC);
      oprot.writeI32(struct.bottom);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(LEFT_FIELD_DESC);
      oprot.writeI32(struct.left);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FaceInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FaceInfoTupleScheme getScheme() {
      return new FaceInfoTupleScheme();
    }
  }

  private static class FaceInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<FaceInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FaceInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetEncoding()) {
        optionals.set(0);
      }
      if (struct.isSetTop()) {
        optionals.set(1);
      }
      if (struct.isSetRight()) {
        optionals.set(2);
      }
      if (struct.isSetBottom()) {
        optionals.set(3);
      }
      if (struct.isSetLeft()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetEncoding()) {
        {
          oprot.writeI32(struct.encoding.size());
          for (double _iter4 : struct.encoding)
          {
            oprot.writeDouble(_iter4);
          }
        }
      }
      if (struct.isSetTop()) {
        oprot.writeI32(struct.top);
      }
      if (struct.isSetRight()) {
        oprot.writeI32(struct.right);
      }
      if (struct.isSetBottom()) {
        oprot.writeI32(struct.bottom);
      }
      if (struct.isSetLeft()) {
        oprot.writeI32(struct.left);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FaceInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.DOUBLE);
          struct.encoding = new java.util.ArrayList<java.lang.Double>(_list5.size);
          double _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = iprot.readDouble();
            struct.encoding.add(_elem6);
          }
        }
        struct.setEncodingIsSet(true);
      }
      if (incoming.get(1)) {
        struct.top = iprot.readI32();
        struct.setTopIsSet(true);
      }
      if (incoming.get(2)) {
        struct.right = iprot.readI32();
        struct.setRightIsSet(true);
      }
      if (incoming.get(3)) {
        struct.bottom = iprot.readI32();
        struct.setBottomIsSet(true);
      }
      if (incoming.get(4)) {
        struct.left = iprot.readI32();
        struct.setLeftIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

